// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package models

import ()

type Configuration struct {
	Did        string
	Service    string
	RefreshJwt string
	Enabled    bool
	PostTtl    int32
}
